apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-backend
  namespace: leave-management
  labels:
    app: leave-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-backend
  template:
    metadata:
      labels:
        app: leave-backend
    spec:
      serviceAccountName: leave-backend-ksa

      containers:
        - name: backend
          image: asia-south1-docker.pkg.dev/pe3-devops-training-svaranasi/pe3-app-images/leave-management-backend:v1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000

          envFrom:
            - configMapRef:
                name: leave-backend-config
            - secretRef:
                name: leave-app-secret

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

        - name: cloud-sql-auth-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.18.2
          imagePullPolicy: IfNotPresent

          args:
            - "--structured-logs"
            - "--port=3306"
            - "pe3-devops-training-svaranasi:asia-south1:leave-management-mysql"

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
