apiVersion: v1
kind: Service
metadata:
  name: leave-frontend-service
  namespace: leave-management
  labels:
    app: leave-frontend
spec:
  type: LoadBalancer
  selector:
    app: leave-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
