apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-frontend
  namespace: leave-management
  labels:
    app: leave-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-frontend
  template:
    metadata:
      labels:
        app: leave-frontend
    spec:
      containers:
        - name: frontend
          image: asia-south1-docker.pkg.dev/pe3-devops-training-svaranasi/pe3-app-images/leave-management-frontend:v2
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          startupProbe:
            httpGet:
              path: /health
              port: 80
            failureThreshold: 20
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
